#!/bin/bash

#SBATCH --job-name=extractor_cordis_contenttype=projectANDSTAR
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/logs/extractor_contenttype=projectANDSTAR_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

python src/extractors/run_cordis_extractor.py -r 1