#!/bin/bash

#SBATCH --job-name=extractor_cordis_contenttype=projectANDSTAR
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/extractor_contenttype=projectANDSTAR_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

# python src/extractors/extractor.py -r 1
python src/analysis/jobs/file_structure_analysis.py -q cordis_contenttypeISprojectANDSTAR