#!/bin/bash

#SBATCH --job-name=enrichment_topic_modelling
#SBATCH --partition=standard
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --output=/home/lu72hip/DIGICHer/dh_pipeline/data/runs/enrichment/etl_enrichment_topic_modelling_open_alex_keyword%j.log

pg_ctl -D $PGDATA stop

sleep 10

pg_ctl -D $PGDATA start

cd /home/lu72hip/DIGICHer/dh_pipeline || exit
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

cd src/enrichment/topic_modelling || exit
python run_topic_model_open_alex_keyword.py