#!/bin/bash

#SBATCH --job-name=enrichment_geolocation
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/enrichment/etl_enrichment_geolocation_%j.log

pg_ctl -D $PGDATA stop

sleep 5

pg_ctl -D $PGDATA start


cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

cd src/enrichment
python get_geolocations_to_csv.py