#!/bin/bash

#SBATCH --job-name=cordis_transformer
#SBATCH --partition=fat
#SBATCH --time=4:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/transformation/cordis_ch_%j.log

### CleanUp

cleanup() {
    echo "Cleaning up..."
    pg_ctl stop -D "$PGDATA"
    exit
}
trap cleanup EXIT SIGINT SIGTERM

### Setup

echo "Running script ..."
echo "${PGDATA:?not set}"
echo "Stopping DB in case its running somewhere else"
pg_ctl -D $PGDATA stop
sleep 10

echo "Starting DB on this node"
pg_ctl -D $PGDATA start -l /vast/lu72hip/pgsql/logfile
sleep 10
echo "PostgreSQL status:"
pg_ctl status -D $PGDATA

### Scripts

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline || exit

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

psql -d db_digicher_v2 -p 5433 -f sql/sources/cordis/transform_to_core.sql
