name: 'transformation'
version: '1.0.0'
profile: 'transformation'

# These configurations specify where dbt should look for different types of files.
model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  transformation:
    # Global defaults
    +materialized: table
    +on_schema_change: "sync_all_columns"

    staging:
      +materialized: view
      arxiv:
        +schema: arxiv_staging

    intermediate:
      +materialized: table
      arxiv:
        +schema: arxiv_intermediate
      cordis:
        +schema: cordis_intermediate
      # coreac:
      #   +schema: coreac_intermediate
      # openaire:
      #   +schema: openaire_intermediate

    marts:
      +materialized: table
      +schema: core

vars:
  # Source schemas
  arxiv_schema: 'arxiv'
  cordis_schema: 'cordis'
  coreac_schema: 'coreac'
  openaire_schema: 'openaire'

  # Target schemas
  staging_schema: 'staging'
  intermediate_schema: 'intermediate'
  core_schema: 'core'

