#!/bin/bash

#SBATCH --job-name=cordis_extractor
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/extractors/cordis_%j.log

while true; do
    cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline || exit
    source venv/bin/activate

    echo "Current user: $(whoami)"
    echo "Current directory: $(pwd)"
    echo "Python version: $(python --version)"
    echo "Run started at: $(date)"

    python src/sources/cordis/extractor.py
    python src/analysis/jobs/file_structure_analysis.py -q cordis_culturalORheritage

    echo "Run stopped at: $(date)"
    echo "Sleeping for 1 hour before next run..."

    sleep 3600
done