#!/bin/bash

#SBATCH --job-name=extractor_openaire_cultural
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/extractor/etl_openaire_cultural_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

python src/sources/openaire/extractor.py -r 0
python src/analysis/jobs/file_structure_analysis.py -q openaire_cultural