#!/bin/bash

#SBATCH --job-name=analysis_fs
#SBATCH --partition=standard
#SBATCH --time=02:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/analysis/file_structure_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline || exit
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"


python src/analysis/jobs/file_structure_analysis.py -q cordis_culturalORheritage
python src/analysis/jobs/file_structure_analysis.py -q core_LBLBcomputingANDculturalRBORLBcomputingANDheritageRBRB
python src/analysis/jobs/file_structure_analysis.py -q arxiv_allCOLONcomputingPLUSANDPLUSLBallCOLONhumanitiesPLUSORPLUSallCOLONheritageRB
python src/analysis/jobs/file_structure_analysis.py -q openaire_cultural
python src/analysis/jobs/file_structure_analysis.py -q openaire_heritage