#!/bin/bash

#SBATCH --job-name=analysis_tf
#SBATCH --partition=standard
#SBATCH --time=02:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/analysis/tag_frequency_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

#python src/analysis/jobs/tag_frequency_analysis.py -q cordis_contenttypeISprojectANDSTAR
python src/analysis/jobs/tag_frequency_analysis.py -q cordis_culturalORheritage

python src/analysis/jobs/tag_frequency_analysis.py -q arxiv_allCOLONcomputingPLUSANDPLUSLBallCOLONhumanitiesPLUSORPLUSallCOLONheritageRB

python src/analysis/jobs/tag_frequency_analysis.py -q core_LBLBcomputingANDculturalRBORLBcomputingANDheritageRBRB