#!/bin/bash

#SBATCH --job-name=analysis
#SBATCH --partition=standard
#SBATCH --time=02:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/analysis_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

# python src/analysis/jobs/basic_stats_job.py -q cordis_contenttypeISprojectANDSTAR
python src/analysis/jobs/basic_stats_job.py -q cordis_culturalORheritage

# python src/analysis/jobs/basic_stats_job.py -q core_LBLBcomputingANDculturalRBORLBcomputingANDheritageRBRB

# python src/analysis/jobs/basic_stats_job.py -q arxiv_allCOLONcomputingPLUSANDPLUSLBallCOLONhumanitiesPLUSORPLUSallCOLONheritageRB