#!/bin/bash

#SBATCH --job-name=analysis
#SBATCH --partition=standard
#SBATCH --time=02:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/logs/analysis_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

python src/analysis/analysis.py