#!/bin/bash

#SBATCH --job-name=extractor_cordis_culturalORHeritage
#SBATCH --partition=long
#SBATCH --time=240:00:00
#SBATCH --output=/home/lu72hip/DIGICHer/DIGICHer_Pipeline/data/runs/extractor_cordis_culturalORHeritage_%j.log

cd /home/lu72hip/DIGICHer/DIGICHer_Pipeline
source venv/bin/activate

echo "Current user: $(whoami)"
echo "Current directory: $(pwd)"
echo "Python version: $(python --version)"

python src/extractors/cordis_extractor.py -r 0
python src/analysis/jobs/basic_stats_job.py -q cordis_culturalORheritage